name:                thoth
version:             0.1.0.0
github:              "deividrvale/thoth"
license:             MIT
author:              "Deivid Vale"
maintainer:          "deividrodriguesvale@gmail.com"
copyright:           "2022 Deivid Vale"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Symbolic Computation

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/deividrvale/thoth#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  thoth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thoth

tests:
  thoth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thoth
